name: Build Game Executables

on:
  push:
    branches: [ "main" ]   # adjust if your default branch is different
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onedir --windowed main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.os }}
          path: dist/*

